document.getElementById("container").style.backgroundColor="#12406A"
document.querySelectorAll(".box")[0].style.backgroundColor="#EB8F90"
document.querySelectorAll(".box")[1].style.backgroundColor="##FFB471"
document.querySelectorAll(".box")[2].style.backgroundColor="#ADBED2"
document.body.style.backgroundColor="#CCFFFF"